name: Read JSON file

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: Environment to provision infra
        required: true
        default: 'qa'
        type: choice
        options:
        - qa
        - prod

jobs:
  read-json:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read JSON file
        id: env_values
        env:
          VAR1_FILE: "./.github/${{ inputs.Environment }}_param.json"
        run: |
          $json = Get-Content -Path ${{ env.VAR1_FILE }} -Raw | ConvertFrom-Json
          "data_rg=$($json.parameters.data_rg.value)" >> $env:GITHUB_OUTPUT
          "userAssignedIdentity=$json.parameters.userAssignedIdentityname.value" >> $env:GITHUB_OUTPUT
          "StorageAccount=$json.parameters.storageAccountName.value" >> $env:GITHUB_OUTPUT

      - name: write
        run: |
          Write-Host "${{ steps.env_values.outputs.data_rg }}"