name: Bicep

on:
  workflow_dispatch:
    inputs:
      doDeployBotServer:
        description: 'Build/Deploy Self-Serve Bot Server App?'
        required: true
        default: true
        type: boolean

  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  # This job will call a template workflow for each environment defined in the matrix.
  deployment:
    strategy:
      matrix:
        deploymentEnvironment:
          - environmentName: Integration
            githubEnvironment: Non-Production Integration

          - environmentName: QA
            githubEnvironment: Non-Production QA

          # - environmentName: [Name of environment]
          #   githubEnvironment: [Name of the environment in GitHub]
          #   azureClientId: [Azure client ID]
          #   azureTenantId: [Azure tenant ID]
          #   azureSubscriptionId: [Azure subscription ID]
          #   resourceGroup: [Name of the Azure resource group]
          #   keyvaultName: [Name of the Azure key vault]
          #   acrName: [Name of the Azure Container Registry]
          #   containerAppEnvironment: [Name of the Azure container app environment]
          #   dbConnectionString: [Connection string to the database (without any secrets)]
          #   containerAppNameEnvironmentSetup: [Name of the container resource of the environment setup app]
          #   containerAppNameBotServer: [Name of the container resource of the bot server]

    uses: ./.github/workflows/bicep-ci.yaml
    name: Deploy ${{ matrix.deploymentEnvironment.environmentName }}
    secrets: inherit
    with:
      environmentName: "${{ matrix.deploymentEnvironment.environmentName }}"
      githubEnvironment: "${{ matrix.deploymentEnvironment.githubEnvironment }}"
      