name: Dynamic Jobs

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'List of environments (comma-separated)'
        required: true

jobs:
  dynamic-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Process environments input
        run: |
          ENVS=(${GITHUB_EVENT_INPUTS_environments//,/ })
          for env in "${ENVS[@]}"; do
            echo "Creating job for $env"
            echo "  name: $env"
            echo "  runs-on: ubuntu-latest"
            echo "  steps:"
            echo "    - name: Deploy to $env"
            echo "      run: |"
            echo "        # Deployment logic for $env goes here"
            echo "        echo 'Deploying to $env'"
          done

      - name: Output jobs
        run: |
          echo "jobs:"
          for env in "${ENVS[@]}"; do
            echo "  $env:"
            echo "    runs-on: ubuntu-latest"
            echo "    steps:"
            echo "      - name: Deploy to $env"
            echo "        run: |"
            echo "          # Deployment logic for $env goes here"
            echo "          echo 'Deploying to $env'"
          done