name: Dynamic Jobs

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'List of environments (comma-separated)'
        required: true

jobs:
  dynamic-jobs:
    runs-on: ubuntu-latest
    matrix:
      env: ${{ github.event.inputs.environments.split(',') }}

    steps:
      - name: Deploy to ${{ matrix.env }}
        run: |
          # Deployment logic for ${{ matrix.env }} goes here
          echo "Deploying to ${{ matrix.env }}"