name: Test

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: Environment to provision infra
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod
jobs:
  my-job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Environment }} # Set the environment variable
    steps:
      - name: Load variables
        env:
          ENV: ${{ inputs.Environment }}
          VAR1_FILE: $GITHUB_WORKSPACE/.github/variables.yml
        run: |
          echo "Loading variables from $VAR1_FILE"
          vars=$(jq -r '.environments[] | select(.name == env.ENV) | .vars' $VAR1_FILE)
          echo "$vars" >> $GITHUB_ENV
      - name: Print variables
        run: |
          echo "VAR1: $VAR1"
          echo "VAR2: $VAR2"