name: Trigger Workflow with Secret

on:
    workflow_dispatch:
        inputs:
            target_workflow:
                description: "Target workflow file to trigger"
                required: true
                default: "dummy-workflow.yaml"
                type: string
            message:
                description: "Custom message for the workflow"
                required: false
                default: "Triggered from GitHub Pages"
                type: string
            environment:
                description: "Target environment"
                required: false
                default: "development"
                type: choice
                options:
                    - development
                    - staging
                    - production

    # Allow trigger from repository dispatch (for web interface)
    repository_dispatch:
        types: [web-trigger]

jobs:
    trigger-target-workflow:
        runs-on: ubuntu-latest

        steps:
            - name: Trigger target workflow
              run: |
                  # Set variables from inputs or client_payload
                  if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
                    TARGET_WORKFLOW="${{ github.event.client_payload.target_workflow || 'dummy-workflow.yaml' }}"
                    MESSAGE="${{ github.event.client_payload.message || 'Triggered from GitHub Pages' }}"
                    ENVIRONMENT="${{ github.event.client_payload.environment || 'development' }}"
                  else
                    TARGET_WORKFLOW="${{ github.event.inputs.target_workflow }}"
                    MESSAGE="${{ github.event.inputs.message }}"
                    ENVIRONMENT="${{ github.event.inputs.environment }}"
                  fi

                  echo "🎯 Triggering workflow: $TARGET_WORKFLOW"
                  echo "📝 Message: $MESSAGE"
                  echo "🌍 Environment: $ENVIRONMENT"

                  # Trigger the target workflow using the PAT stored in secrets
                  curl -X POST \
                    -H "Authorization: token ${{ secrets.WORKFLOW_PAT }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    -H "Content-Type: application/json" \
                    "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$TARGET_WORKFLOW/dispatches" \
                    -d "{
                      \"ref\": \"main\",
                      \"inputs\": {
                        \"message\": \"$MESSAGE\",
                        \"environment\": \"$ENVIRONMENT\"
                      }
                    }"

                  if [ $? -eq 0 ]; then
                    echo "✅ Successfully triggered $TARGET_WORKFLOW"
                  else
                    echo "❌ Failed to trigger $TARGET_WORKFLOW"
                    exit 1
                  fi
